# application.yml
server:
  port: 8080

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders:
              - "Origin"
              - "Content-Type"
              - "Accept"
              - "Authorization"
              - "Referer"
            allowedMethods:
              - POST
              - GET
              - OPTIONS
      routes:
        - id: user-service
          uri: lb://USER-MANAGEMENT-SERVICE
          predicates:
            - Path=/users/**

    security:
      oauth2:
        resourceserver:
          jwt:
            jwk-set-uri: http://localhost:9090/.well-known/jwks.json

  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
      instance:
        prefer-ip-address: true

  management:
    endpoints:
      web:
        exposure:
          include: "*"
logging:
  level:
    root: INFO
    org.springframework: INFO
    org.springframework.web: DEBUG
