# application.yml
server:
  port: 8080

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:6060/realms/oekosol
        registration:
          keycloak:
            client-id: solar-gateway
            client-secret: 2YIlZCiJyf2GGKgkBazLKlrUajNzFAHq

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
#    com.netflix.discovery: DEBUG
#    com.netflix.eureka: DEBUG
    org.springframework.cloud.gateway: DEBUG

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

resilience4j:
  circuitbreaker:
    instances:
      userManagementCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 100
        permittedNumberOfCallsInHalfOpenState: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: 10000
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
        recordExceptions:
          - java.io.IOException
          - java.util.concurrent.TimeoutException
